(cl:defpackage detection_msgs-msg
  (:use )
  (:export
   "<BOUNDINGBOX>"
   "BOUNDINGBOX"
   "<BOUNDINGBOX2D>"
   "BOUNDINGBOX2D"
   "<BOUNDINGBOXES>"
   "BOUNDINGBOXES"
   "<DETECTION2D>"
   "DETECTION2D"
   "<DETECTION2DARRAY>"
   "DETECTION2DARRAY"
   "<OBJECTHYPOTHESISWITHPOSE>"
   "OBJECTHYPOTHESISWITHPOSE"
  ))

